import type { Collection, Product } from '@/lib/types';

export const COLLECTIONS: Collection[] = [
  { id: 'SEC-01', name: 'DARK SECTOR', slug: 'dark-sector', description: 'Low light / high intent.', tag: 'LIMITED' },
  { id: 'SEC-02', name: 'URBAN MODULE', slug: 'urban-module', description: 'City-ready essentials.', tag: 'CORE' },
  { id: 'SEC-03', name: 'FIELD KIT', slug: 'field-kit', description: 'Built for movement.', tag: 'CORE' },
  { id: 'SEC-04', name: 'ARCHIVE', slug: 'archive', description: 'Past drops.', tag: 'ARCHIVE' },
  { id: 'SEC-05', name: 'PROJECT VOSKHOD', slug: 'project-voshod', description: 'The beginning.', tag: 'LIMITED' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'P-001',
    name: 'TEE / VOSKHOD MARK',
    slug: 'tee-voshod-mark',
    price: 4990,
    category: 'tee',
    collectionId: 'SEC-01',
    image: '/products/tee-1.jpg',
    badge: 'LIMITED',
    inStock: true,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Premium cotton. Tactical cut. Minimal mark.',
  },
  {
    id: 'P-002',
    name: 'HOODIE / NIGHT GRAPHITE',
    slug: 'hoodie-night-graphite',
    price: 9990,
    category: 'hoodie',
    collectionId: 'SEC-02',
    image: '/products/hoodie-1.jpg',
    badge: 'CORE',
    inStock: true,
    sizes: ['M', 'L', 'XL'],
    description: 'Heavyweight. Clean silhouette. Built to last.',
  },
  {
    id: 'P-003',
    name: 'PATCH / SIGNAL',
    slug: 'patch-signal',
    price: 1490,
    category: 'accessory',
    collectionId: 'SEC-03',
    image: '/products/patch-1.jpg',
    badge: 'NEW',
    inStock: true,
    sizes: ['ONE SIZE'],
    description: 'Embroidered patch with velcro backing.',
  },
  {
    id: 'P-004',
    name: 'TEE / SUNRISE CODE',
    slug: 'tee-sunrise-code',
    price: 4990,
    category: 'tee',
    collectionId: 'SEC-05',
    image: '/products/tee-2.jpg',
    badge: 'DROP',
    inStock: false,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Drop piece. Limited quantity.',
  },
];
