import type { Collection, Product } from "./types";

export const collections: Collection[] = [
  {
    id: "col-core",
    slug: "core",
    name: "CORE",
    description: "База и регулярный ассортимент.",
    tag: "CORE",
    coverImage: "https://picsum.photos/seed/voshod-core/1600/900",
  },
  {
    id: "col-drop-001",
    slug: "drop-001",
    name: "DROP 001",
    description: "Лимитированный выпуск. Малый тираж.",
    tag: "DROP",
    coverImage: "https://picsum.photos/seed/voshod-drop/1600/900",
  },
  {
    id: "col-accessories",
    slug: "accessories",
    name: "ACCESSORIES",
    description: "Патчи и аксессуары.",
    tag: "ACCESSORIES",
    coverImage: "https://picsum.photos/seed/voshod-acc/1600/900",
  },
];

export const products: Product[] = [
  {
    id: "p-tee-001",
    slug: "tee-voshod-black",
    name: "Футболка ВОСХОД Black",
    category: "tee",
    price: 6900,
    description: "Плотный хлопок, минималистичный крой.",
    image: "https://picsum.photos/seed/tee1/800/1000",
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    status: "available",
    badge: "NEW",
    collectionId: "col-core",
    specs: {
      code: "VS-TEE-001",
      fabric: "100% хлопок",
      density: "240 г/м²",
      print: "Шелкография",
      color: "Black",
    },
  },
  {
    id: "p-patch-001",
    slug: "patch-voshod-ember",
    name: "Патч ВОСХОД EMBER",
    category: "patch",
    price: 1900,
    description: "ПВХ патч на липучке.",
    image: "https://picsum.photos/seed/patch1/800/1000",
    sizes: ["ONE SIZE"],
    inStock: true,
    status: "available",
    collectionId: "col-accessories",
    specs: {
      code: "VS-PATCH-001",
      color: "EMBER",
      print: "3D PVC",
    },
  },
  {
    id: "p-cap-001",
    slug: "cap-voshod-graphite",
    name: "Кепка ВОСХОД Graphite",
    category: "cap",
    price: 4900,
    description: "Лаконичная кепка с вышивкой.",
    image: "https://picsum.photos/seed/cap1/800/1000",
    sizes: ["ONE SIZE"],
    inStock: false,
    status: "sold out",
    badge: "SOLD OUT",
    collectionId: "col-drop-001",
    specs: {
      code: "VS-CAP-001",
      color: "Graphite",
      print: "Вышивка",
    },
  },
];
